T0001 - Get service to show number's name
WertonGuimaraes/numerosExtensos pull request #1
Opened 2019-11-08 17:33 UTC by WertonGuimaraes

2019-11-08 23:01 UTC, mzr-certi requested changes

2019-11-08 23:01 UTC, mzr-certi commented on README.md
> +{"erro":"Só é aceitado números inteiros entre LIMITE_MINIMO e LIMITE_MAXIMO."}
nitpick: "são aceitos"

2019-11-08 23:01 UTC, mzr-certi commented on api/numero.py
> +#     print converte_numero_inteiro_para_extenso(numero)
hmmm

2019-11-08 23:01 UTC, mzr-certi commented on docker-compose.yml
> +    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
onde que isso é usado?!

2019-11-08 23:01 UTC, mzr-certi commented on util/constants.py
> +centenas = ("", "cento", "duzentos", "trezentos", "quatrocentos", "quinhentos", "seicentos", "setecentos", "oitocentos",
typo - seiscentos

2019-11-08 23:01 UTC, mzr-certi commented on util/constants.py
> +dezenas_especiais = ("", "onze", "doze", "treze", "cartoze", "quinze", "dezeseis", "dezesete", "dezoito", "dezenove")
3 typos nesse array

2019-11-11 04:10 UTC, WertonGuimaraes commented on README.md
> +{"erro":"Só é aceitado números inteiros entre LIMITE_MINIMO e LIMITE_MAXIMO."}
Resolvido.

2019-11-11 04:10 UTC, WertonGuimaraes commented on api/numero.py
> +#     print converte_numero_inteiro_para_extenso(numero)
Ops. Removido.

2019-11-11 04:12 UTC, WertonGuimaraes commented on docker-compose.yml
> +    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
De fato! Não esta sendo usado. *Eu estava estudando dois containers em um app e acebei esquecendo de remover. 
obrigado, foi removido.

2019-11-11 04:13 UTC, WertonGuimaraes commented on util/constants.py
> +centenas = ("", "cento", "duzentos", "trezentos", "quatrocentos", "quinhentos", "seicentos", "setecentos", "oitocentos",
Resolvido. Aproveitei o ajeitei `tres` para `três`.

2019-11-11 04:13 UTC, WertonGuimaraes commented on util/constants.py
> +dezenas_especiais = ("", "onze", "doze", "treze", "cartoze", "quinze", "dezeseis", "dezesete", "dezoito", "dezenove")
Resolvido.

2019-11-11 21:45 UTC, mzr-certi commented
👍

2019-11-11 21:47 UTC, merged